name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main"]
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: [uses: fastai/workflows/quarto-ghp@master]
